Feature: 프로젝트 추가 세팅
YAPP-Github/23rd-Android-Team-1-BE pull request #2
Opened 2023-11-15 15:29 UTC by wjdtkdgns

## 개요
- close #1

## 작업사항
- 이슈, 풀리퀘 템플릿 추가했습니다
- ktlint, jacoco, sonarqube 세팅했습니다.
- CI workflow 부분에 ktlint 체크, sonarcloud 분석 로직 추가했습니다.

## 변경로직

* 추가
파일명과 해당 파일에 존재하는 클래스의 이름이 달라서 ktlint에서 에러를 띄웁니다.
변경 필요할 것 같습니다.

2023-11-15 15:44 UTC, DongGeon0908 requested changes

2023-11-15 15:44 UTC, DongGeon0908 commented on build.gradle.kts
> +    testImplementation("io.kotest:kotest-runner-junit5:5.7.2")
dependencyversion object에서 버저닝 관리하는게 좋을 것 같아욤

2023-11-15 15:44 UTC, DongGeon0908 commented on build.gradle.kts
> +
요기 신규 진행한거 저도 테스트를 해봐야 할 것 같어요

2023-11-15 15:44 UTC, DongGeon0908 commented on src/main/kotlin/com/goofy/boilerplate/config/database/BoilerPlateDatabaseConfig.kt
>      fun boilerplateNamedParameterJdbcTemplate(
코틀린에서는 ,쓰는 거를 더 권장해요
이유는 ,쓰면 신규로 무언가 추가될때, 추가된 부분만 커밋로그로 등록되거든요

2023-11-15 15:44 UTC, DongGeon0908 commented on src/main/kotlin/com/goofy/boilerplate/health/presentation/HealthResource.kt
> -
eof 입니다.
의도한거에요

2023-11-15 15:45 UTC, DongGeon0908 requested changes
몇가지 리뷰사항 올렸습니다

2023-11-15 15:45 UTC, DongGeon0908 commented on src/test/resources/config/application-dev.yml
> +# Spring Boot Configuration for the dev profile
해당 파일이 필요한 이유가 궁금해요
테스트에 대한 dev가 있나요??

2023-11-15 16:16 UTC, wjdtkdgns commented on src/test/resources/config/application-dev.yml
> +# Spring Boot Configuration for the dev profile
일단 테스트 돌아가게만 해둘려고 yml 파일 다 가져왔어요.
수정 필요합니다!

2023-11-15 17:15 UTC, DongGeon0908 commented
boot3, jdk 17 반영했어요.
swagger의 경우에는 boot2에서 쓰던 것들이 좀 다르긴 한데, 괜찮을 것 같네요.

2023-11-16 00:20 UTC, DongGeon0908 commented
merge!!

2023-11-16 03:44 UTC, DongGeon0908 commented
완료되었다면, merge를!

2023-11-16 03:50 UTC, DongGeon0908 approved these changes

2023-11-16 04:19 UTC, merged